In [1]:
import torch

In [2]:
# By default torch takes gradient as false so have to change that it True
x = torch.randn(3, requires_grad = True)
print(x)

tensor([-0.4767, -1.2095,  0.6034], requires_grad=True)


In [3]:
# Mathematical Operation
y = x + 2
print(y) 
# Above we add values in backward propogation

y = x * 2
print(y)

# Above we multiply in backward propagation

tensor([1.5233, 0.7905, 2.6034], grad_fn=<AddBackward0>)
tensor([-0.9535, -2.4190,  1.2068], grad_fn=<MulBackward0>)


In [4]:
# Backward function for this we have to make sure requires_grad is True
z = y.mean()
# For backpropogation the values have to be scalar and have to run required_grad line for second time for backward()
z.backward()
print(x.grad)

tensor([0.6667, 0.6667, 0.6667])


In [9]:
# Sometimes we have to remove the gradient history so to do this we have 3 Options
# 1st is requires_grad(False)
req_x = torch.randn(3, requires_grad = True)
print(req_x)
# Remove the gradient history
req_x.requires_grad_(False)
print(req_x)

tensor([-0.0418, -0.4191,  0.2097], requires_grad=True)
tensor([-0.0418, -0.4191,  0.2097])


In [10]:
# 2nd use detach() function
y = req_x.detach()
print(y)

tensor([-0.0418, -0.4191,  0.2097])


In [12]:
# 3rd Option
with torch.no_grad():
    y = x + 2
    print(y)

tensor([1.5233, 0.7905, 2.6034])


In [14]:
# Let's train a dummy example
weights = torch.ones(3, requires_grad = True)
for i in range(2):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)
    # It clears the stored values or empty the tensor every time otherwise our model runs incorrectly
    weights.grad.zero_()

tensor([3., 3., 3.])
tensor([3., 3., 3.])
