In [ ]:
import torch

**Intro to Pytorch**

PyTorch is an open source machine learning framework that allows you to write your own neural networks and optimize them efficiently.

In [ ]:
import time

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.utils.data as data

%matplotlib inline
from IPython.display import set_matplotlib_formats
from matplotlib.colors import to_rgba
from torch import Tensor
from tqdm.notebook import tqdm  # Progress bar

set_matplotlib_formats("svg", "pdf")

In [ ]:
print("Using version" , torch.__version__)

Using version 1.13.1+cu116


PyTorch provides functions that are stochastic like generating random numbers

In [ ]:
torch.manual_seed(42) 

Tensors are the PyTorch equivalent to Numpy arrays, with the addition to also have support for GPU acceleration (more on that later). The name “tensor” is a generalization of concepts you already know. For instance, a vector is a 1-D tensor, and a matrix a 2-D tensor. When working with neural networks, we will use tensors of various shapes and number of dimensions.

In [ ]:
x = Tensor(2,3,4)
print(x)

tensor([[[2.1715e-18, 1.0791e-08, 4.2932e-08, 6.7576e-07],
         [2.6219e-09, 3.1950e+21, 1.3097e-11, 1.0860e-05],
         [2.5785e-09, 2.1271e-07, 2.1707e-18, 4.5447e+30]],

        [[7.0062e+22, 2.1715e-18, 4.5447e+30, 7.0062e+22],
         [2.1707e-18, 1.9284e+31, 3.2314e-18, 1.5462e-04],
         [5.3601e-08, 1.0197e-11, 1.6805e-04, 8.3748e-10]]])


In [ ]:
y = torch.ones
print(y)

<built-in method ones of type object at 0x7f21c16c4420>


In [ ]:
z = Tensor([[1,2],[3,4]])
print(z)
print(z.shape)

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [ ]:
xt = torch.rand(2,3,4)
print(xt)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])


In [ ]:
print(xt.shape)
print(xt.size())

torch.Size([2, 3, 4])
torch.Size([2, 3, 4])


**Tensor to Numpy, and Numpy to Tensor**

Tensors can be converted to numpy arrays, and numpy arrays back to tensors. To transform a numpy array into a tensor, we can use the function torch.from_numpy:

In [ ]:
np_tr = np.array([[1,2],[3,4]])
tensor = torch.from_numpy(np_tr)
print(tensor)

tensor([[1, 2],
        [3, 4]])


In [ ]:
tor = torch.arange(4)
np_arr = tor.numpy()
print(np_arr)

[0 1 2 3]


In [ ]:
x1 = torch.rand(2,3)
x2 = torch.rand(2,3)
y = x1 + x2
print(y)
print(x2)
x2.add_(x1)
print(x2)

tensor([[1.0569, 0.3448, 1.2448],
        [0.7826, 0.8848, 0.8151]])
tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])
tensor([[1.0569, 0.3448, 1.2448],
        [0.7826, 0.8848, 0.8151]])


In [ ]:
x = torch.arange(6)
x = x.view(2,3)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
x = x.permute(1,0)
print(x)

tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [ ]:
over = torch.arange(6).view(2,3)
print(over)

tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
# Matrix Multiply
h = torch.matmul(over,x)
print(h)

tensor([[ 5, 14],
        [14, 50]])


Each node of the computation graph has automatically defined a function for calculating the gradients with respect to its inputs, grad_fn. You can see this when we printed the output tensor y. This is why the computation graph is usually visualized in the reverse direction (arrows point from the result to the inputs

In [ ]:
xty = torch.ones((3,))
print(x.requires_grad)

False


In [ ]:
xty.requires_grad = False
print(x.retains_grad)

False


In [ ]:
x4 = torch.arange(3, dtype = torch.float32 , requires_grad= True)
print("X" , x4)

X tensor([0., 1., 2.], requires_grad=True)


Back Propagation in PyTorch

In [ ]:
bp = torch.tensor(4.0 , requires_grad = True)
bp

tensor(4., requires_grad=True)

In [ ]:
yb = bp**2
yb

tensor(16., grad_fn=<PowBackward0>)

In [ ]:
# For backpropagation
yb.backward()

In [ ]:
# After backpropagation means it does derivation on yb as yb = 2*bp
print(bp.grad)

tensor(8.)


In [ ]:
lst = [[2.,3.,4.] , [5.,6.,7.] , [8.,9.,10]]
mo = torch.tensor(lst, requires_grad = True)

In [ ]:
mo

tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]], requires_grad=True)

In [ ]:
answ = mo**3 + mo**2
answ

tensor([[  12.,   36.,   80.],
        [ 150.,  252.,  392.],
        [ 576.,  810., 1100.]], grad_fn=<AddBackward0>)

In [ ]:
su = answ.sum()
print(su)

tensor(3408., grad_fn=<SumBackward0>)


In [ ]:
su.backward()


In [ ]:
mo.grad

tensor([[ 16.,  33.,  56.],
        [ 85., 120., 161.],
        [208., 261., 320.]])

In [ ]:
torch.cuda.is_available()

False

In [ ]:
# Torch.randn() it gives random integers having mean 0 and variance 1
x = torch.randn(5000,5000)
x