In [14]:
import torch

In [15]:
# torch.empty() returns the tensor filled with uninitialized data
e = torch.empty(3)
print(e)

tensor([0., 0., 0.])


In [16]:
# torch.rand() return the random tensor with specific shape
r = torch.rand(2)
print(r)

tensor([0.1843, 0.1638])


In [17]:
# torch.zeros() return a tensor filled with the scaler value 0 with the shape defined by the variable argument
z = torch.zeros(2)
print(z)

tensor([0., 0.])


In [18]:
# torch.ones() return a tensor filled with the scaler value 1 with the shape defined by the variable argument
o = torch.ones(3)
print(o)

tensor([1., 1., 1.])


In [23]:
rand = torch.ones(2,3)
print(rand.dtype)

# Change the dtype
randchg = torch.ones(2,3 , dtype = torch.int)
print(randchg.dtype)

torch.float32
torch.int32


In [24]:
# To check size of the tensor
print(randchg.size())

torch.Size([2, 3])


In [25]:
# We can create tensor 
ten = torch.tensor([2.5,4.3])
print(ten)

tensor([2.5000, 4.3000])


In [37]:
# Basics Mathematical Operations

# Addition

adx = torch.rand(2,2)
ady = torch.rand(2,2)
print(adx)
print(ady)
adz = adx + ady
print(adz)
adzADD = torch.add(adx,ady)
print(adzADD)

# Subtraction

adxS = torch.rand(2,2)
adyS = torch.rand(2,2)
adzS = adxS - adyS
print(adzS)

adzSUB = torch.sub(adx,ady)
print(adzSUB)

# Same with multiplication mul and division div

tensor([[0.5726, 0.6950],
        [0.0514, 0.3233]])
tensor([[0.9682, 0.9263],
        [0.4995, 0.0851]])
tensor([[1.5409, 1.6213],
        [0.5509, 0.4083]])
tensor([[1.5409, 1.6213],
        [0.5509, 0.4083]])
tensor([[-0.3947,  0.0062],
        [-0.0887,  0.5341]])
tensor([[-0.3956, -0.2313],
        [-0.4481,  0.2382]])


In [49]:
# Inplace Operations
x_inplace = torch.rand(2)
y_inplace = torch.rand(2)
y_inplace.add_(x_inplace)
print(y_inplace)

tensor([1.5771, 0.9524])


In [40]:
# To change the shape
shape_change = torch.rand(3,3)
print(shape_change)
shape_view = shape_change.view(9)
print(shape_view)

tensor([[0.3830, 0.6477, 0.3969],
        [0.9245, 0.9656, 0.9216],
        [0.2953, 0.1599, 0.8289]])
tensor([0.3830, 0.6477, 0.3969, 0.9245, 0.9656, 0.9216, 0.2953, 0.1599, 0.8289])


In [46]:
# To change tenor to numpy
tens = torch.rand(2)
print(tens)
num = tens.numpy()
print(num)
print(type(num))

tensor([0.5644, 0.7616])
[0.56442904 0.7615623 ]
<class 'numpy.ndarray'>


In [50]:
# torch.randn returns a tensor with mean 0 and standard deviation 1
torch.randn(3)

tensor([ 0.0347,  0.2713, -1.0686])